# Generated by Django 3.0.7 on 2020-06-25 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='カテゴリ名')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='タグ名')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('text', models.TextField(verbose_name='問題文')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='画像')),
                ('choice_a', models.CharField(max_length=255, verbose_name='選択肢a')),
                ('choice_b', models.CharField(max_length=255, verbose_name='選択肢b')),
                ('choice_c', models.CharField(max_length=255, verbose_name='選択肢c')),
                ('choice_d', models.CharField(max_length=255, verbose_name='選択肢d')),
                ('correct_answer', models.CharField(choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd')], max_length=1, verbose_name='正解')),
                ('explanation', models.TextField(blank=True, verbose_name='解説')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='問題更新日')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='quiz.Category', verbose_name='カテゴリ')),
                ('tag', models.ManyToManyField(blank=True, to='quiz.Tag', verbose_name='タグ')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_value', models.CharField(choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd')], max_length=1, verbose_name='回答')),
                ('is_correct', models.BooleanField(verbose_name='正誤判定')),
                ('answered_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='回答日')),
                ('answerer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='回答者')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz', verbose_name='回答した問題ID')),
            ],
        ),
    ]
