# Generated by Django 2.2.13 on 2020-06-26 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='問い合わせ名')),
                ('mail', models.EmailField(max_length=240, verbose_name='メールアドレス')),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='quiz',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.Category', verbose_name='カテゴリ'),
        ),
    ]
