# Generated by Django 2.2.13 on 2020-07-01 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0002_auto_20200626_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_category', models.CharField(choices=[('a', 'a,問題間違いについて'), ('b', 'b,著作権に関して'), ('c', 'c,不快な内容だった'), ('d', 'd,その他')], max_length=1, verbose_name='報告種別')),
                ('message', models.TextField()),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='報告日')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz', verbose_name='報告の問題ID')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='報告者')),
            ],
        ),
    ]
